left_frame:
    username:   "Deansfa"
    source:     "{{own}}"
    author:   "{{User:Deansfa/Credit}}"
    categories: "Photographs by Deansfa|2021 images by Deansfa"
    licence:    "{{self|cc-by-sa-4.0}}"
